spring:
    data:
        redis:
            repositories:
                enabled: true
    redis:
        host: localhost
        port: 6379
    datasource:
        url: jdbc:mariadb://localhost:3306/srs
        driver-class-name: org.mariadb.jdbc.Driver
        #username: root
        #password: root
        username: srs
        password: srs123!!
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

logging:
    config: classpath:logback-local.xml
