spring:
    datasource:
        url: jdbc:mariadb://${DB_ADDRESS}:3306/${DB_DATABASE}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

logging:
    config: classpath:logback-dev.xml
