spring:
    data:
        redis:
            repositories:
                enabled: true
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        sql-script-encoding: UTF-8
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

logging:
    config: classpath:logback-dev.xml
